import samsungM52 from "@/assets/samsung-m52.jpg";
import spenNote8 from "@/assets/spen-note8.jpg";

export type ProductType = "hp-bekas" | "sparepart" | "tablet";

export type ProductGrade = "A" | "B+" | "B" | "C";

export interface InspectionItem {
  label: string;
  status: "Normal" | "Minus";
  note?: string;
}

export const PRODUCT_TYPE_LABELS: Record<ProductType, string> = {
  "hp-bekas": "HP Bekas",
  sparepart: "Sparepart",
  tablet: "Tablet",
};

export interface PhoneModel {
  id: string;
  brandId: string;
  name: string;
  slug: string;
  releaseYear: number;
}

export interface PhoneBrand {
  id: string;
  name: string;
  slug: string;
  logo: string;
  models: PhoneModel[];
}

export interface SparePartCategory {
  id: string;
  name: string;
  slug: string;
  icon: string;
  description: string;
}

export interface Product {
  id: string;
  sellerId: string;
  type: ProductType;
  name: string;
  slug: string;
  categoryId: string | null;
  compatibleWith: string[];
  brandId: string;
  modelId: string | null;
  condition: "mulus" | "normal" | "ori-copotan" | "compatible";
  conditionLabel: string;
  conditionNote: string;
  grade?: ProductGrade;
  defects?: string[];
  inspection?: InspectionItem[];
  accessories?: string[];
  tested?: boolean;
  isOriginal?: boolean;
  quality?: string;
  description: string;
  specifications: Record<string, string>;
  price: number;
  compareAtPrice: number | null;
  stock: number;
  images: string[];
  warranty: string;
  weight: number;
  rating: number;
  reviewCount: number;
  soldCount: number;
  isFeatured: boolean;
  isActive: boolean;
  tags: string[];
  createdAt: Date;
}

export interface Seller {
  id: string;
  storeName: string;
  slug: string;
  ownerName: string;
  avatar: string;
  description: string;
  city: string;
  rating: number;
  ratingCount: number;
  totalSold: number;
  productCount: number;
  responseRate: number;
  responseTime: string;
  isVerified: boolean;
  joinedAt: Date;
  operationalHours: string;
  whatsapp: string;
  bannerImage: string;
}

export const mockSeller: Seller = {
  id: "seller-mubarok",
  storeName: "Mubarok Smartphone Sales & Service",
  slug: "mubarok-sms",
  ownerName: "Imam",
  avatar: "",
  description: "Menyediakan smartphone dan sparepart bekas bergaransi. Terima tukar-tambah.",
  city: "Blora, Jawa Tengah",
  rating: 4.9,
  ratingCount: 127,
  totalSold: 342,
  productCount: 18,
  responseRate: 100,
  responseTime: "< 1 jam",
  isVerified: true,
  joinedAt: new Date("2025-01-01"),
  operationalHours: "Senin–Sabtu 09.00–15.00",
  whatsapp: "62895604901090",
  bannerImage: "",
};

export const mockBrands: PhoneBrand[] = [
  {
    id: "brand-samsung",
    name: "Samsung",
    slug: "samsung",
    logo: "",
    models: [
      {
        id: "sam-m52",
        brandId: "brand-samsung",
        name: "Galaxy M52",
        slug: "galaxy-m52",
        releaseYear: 2021,
      },
      {
        id: "sam-note8",
        brandId: "brand-samsung",
        name: "Galaxy Note 8",
        slug: "galaxy-note-8",
        releaseYear: 2017,
      },
      {
        id: "sam-a32",
        brandId: "brand-samsung",
        name: "Galaxy A32",
        slug: "galaxy-a32",
        releaseYear: 2021,
      },
      {
        id: "sam-a53",
        brandId: "brand-samsung",
        name: "Galaxy A53",
        slug: "galaxy-a53",
        releaseYear: 2022,
      },
      {
        id: "sam-a12",
        brandId: "brand-samsung",
        name: "Galaxy A12",
        slug: "galaxy-a12",
        releaseYear: 2021,
      },
      {
        id: "sam-a22",
        brandId: "brand-samsung",
        name: "Galaxy A22",
        slug: "galaxy-a22",
        releaseYear: 2021,
      },
      {
        id: "sam-s20",
        brandId: "brand-samsung",
        name: "Galaxy S20 FE",
        slug: "galaxy-s20-fe",
        releaseYear: 2020,
      },
      {
        id: "sam-s23",
        brandId: "brand-samsung",
        name: "Galaxy S23",
        slug: "galaxy-s23",
        releaseYear: 2023,
      },
    ],
  },
  {
    id: "brand-xiaomi",
    name: "Xiaomi",
    slug: "xiaomi",
    logo: "",
    models: [
      {
        id: "xmi-redmi9",
        brandId: "brand-xiaomi",
        name: "Redmi 9",
        slug: "redmi-9",
        releaseYear: 2020,
      },
      {
        id: "xmi-redmi10",
        brandId: "brand-xiaomi",
        name: "Redmi 10",
        slug: "redmi-10",
        releaseYear: 2021,
      },
      {
        id: "xmi-note11",
        brandId: "brand-xiaomi",
        name: "Redmi Note 11",
        slug: "redmi-note-11",
        releaseYear: 2022,
      },
      {
        id: "xmi-poco-m3",
        brandId: "brand-xiaomi",
        name: "POCO M3",
        slug: "poco-m3",
        releaseYear: 2020,
      },
    ],
  },
  {
    id: "brand-oppo",
    name: "Oppo",
    slug: "oppo",
    logo: "",
    models: [
      { id: "oppo-a54", brandId: "brand-oppo", name: "A54", slug: "a54", releaseYear: 2021 },
      { id: "oppo-a16", brandId: "brand-oppo", name: "A16", slug: "a16", releaseYear: 2021 },
      { id: "oppo-a76", brandId: "brand-oppo", name: "A76", slug: "a76", releaseYear: 2022 },
    ],
  },
  {
    id: "brand-vivo",
    name: "Vivo",
    slug: "vivo",
    logo: "",
    models: [
      { id: "vivo-y20", brandId: "brand-vivo", name: "Y20", slug: "y20", releaseYear: 2020 },
      { id: "vivo-y21", brandId: "brand-vivo", name: "Y21", slug: "y21", releaseYear: 2021 },
      { id: "vivo-y33s", brandId: "brand-vivo", name: "Y33s", slug: "y33s", releaseYear: 2021 },
    ],
  },
  {
    id: "brand-realme",
    name: "Realme",
    slug: "realme",
    logo: "",
    models: [
      { id: "realme-c21", brandId: "brand-realme", name: "C21", slug: "c21", releaseYear: 2021 },
      { id: "realme-8i", brandId: "brand-realme", name: "8i", slug: "8i", releaseYear: 2021 },
      {
        id: "realme-narzo50",
        brandId: "brand-realme",
        name: "Narzo 50",
        slug: "narzo-50",
        releaseYear: 2022,
      },
    ],
  },
  {
    id: "brand-iphone",
    name: "iPhone",
    slug: "iphone",
    logo: "",
    models: [
      {
        id: "iphone-se2020",
        brandId: "brand-iphone",
        name: "iPhone SE 2020",
        slug: "iphone-se-2020",
        releaseYear: 2020,
      },
      {
        id: "iphone-xr",
        brandId: "brand-iphone",
        name: "iPhone XR",
        slug: "iphone-xr",
        releaseYear: 2018,
      },
      {
        id: "iphone-11",
        brandId: "brand-iphone",
        name: "iPhone 11",
        slug: "iphone-11",
        releaseYear: 2019,
      },
    ],
  },
  {
    id: "brand-tecno",
    name: "Tecno",
    slug: "tecno",
    logo: "",
    models: [
      {
        id: "tecno-spark7",
        brandId: "brand-tecno",
        name: "Spark 7",
        slug: "spark-7",
        releaseYear: 2021,
      },
      {
        id: "tecno-pova2",
        brandId: "brand-tecno",
        name: "Pova 2",
        slug: "pova-2",
        releaseYear: 2021,
      },
    ],
  },
  {
    id: "brand-infinix",
    name: "Infinix",
    slug: "infinix",
    logo: "",
    models: [
      {
        id: "infinix-note10",
        brandId: "brand-infinix",
        name: "Note 10",
        slug: "note-10",
        releaseYear: 2021,
      },
      {
        id: "infinix-hot11",
        brandId: "brand-infinix",
        name: "Hot 11",
        slug: "hot-11",
        releaseYear: 2021,
      },
    ],
  },
];

export const mockCategories: SparePartCategory[] = [
  {
    id: "cat-lcd",
    name: "LCD / Display",
    slug: "lcd-display",
    icon: "📱",
    description: "LCD, AMOLED, touchscreen",
  },
  {
    id: "cat-baterai",
    name: "Baterai",
    slug: "baterai",
    icon: "🔋",
    description: "Baterai original dan compatible",
  },
  {
    id: "cat-charging",
    name: "Charging Port",
    slug: "charging-port",
    icon: "⚡",
    description: "Konektor charger, flex charging",
  },
  {
    id: "cat-casing",
    name: "Casing & Frame",
    slug: "casing-frame",
    icon: "🔲",
    description: "Back cover, middle frame, housing",
  },
  {
    id: "cat-kamera",
    name: "Kamera",
    slug: "kamera",
    icon: "📷",
    description: "Modul kamera depan & belakang",
  },
  {
    id: "cat-flex",
    name: "Flex Cable",
    slug: "flex-cable",
    icon: "🔌",
    description: "Flexible kamera, tombol, sensor",
  },
  {
    id: "cat-audio",
    name: "Speaker & Mic",
    slug: "speaker-mic",
    icon: "🔊",
    description: "Loud speaker, earpiece, mikrofon",
  },
  {
    id: "cat-ic",
    name: "IC & Board",
    slug: "ic-board",
    icon: "🔧",
    description: "IC power, IC charging, mainboard",
  },
  {
    id: "cat-aksesori",
    name: "Aksesori",
    slug: "aksesori",
    icon: "🖊️",
    description: "S Pen, stylus, aksesori HP lainnya",
  },
];

export const mockProducts: Product[] = [
  // ========== HP BEKAS ==========
  {
    id: "hp-001",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Samsung Galaxy M52 5G Bekas",
    slug: "samsung-galaxy-m52-5g-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-samsung",
    modelId: "sam-m52",
    condition: "normal",
    conditionLabel: "Normal",
    conditionNote: "Mesin mulus, belum pernah servis. Layar non AMOLED.",
    grade: "B+",
    defects: ["Frame kanan terdapat gores ringan", "Back cover bekas pemakaian."],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
      { label: "Fingerprint", status: "Normal" },
      { label: "NFC", status: "Normal" },
    ],
    accessories: ["Unit", "Charger"],
    description:
      "Samsung Galaxy M52 5G bekas kondisi normal. Mesin mulus belum pernah servis. Layar 6.7 inch Super AMOLED 120Hz. Snapdragon 778G, RAM 6GB, storage 128GB. Baterai 5000mAh. Garansi toko 3 hari.",
    specifications: {
      Merek: "Samsung",
      Tipe: "Galaxy M52 5G",
      Chipset: "Snapdragon 778G",
      RAM: "6 GB",
      Storage: "128 GB",
      Baterai: "5000 mAh",
      Layar: "6.7 inch Super AMOLED 120Hz",
      "Kamera Belakang": "64 MP + 12 MP + 5 MP",
      "Kamera Depan": "32 MP",
      "Kondisi Mesin": "Normal, belum pernah servis",
      Garansi: "3 hari garansi toko",
    },
    price: 1750000,
    compareAtPrice: 2200000,
    stock: 1,
    images: [samsungM52],
    warranty: "3 hari garansi toko",
    weight: 300,
    rating: 4.8,
    reviewCount: 12,
    soldCount: 24,
    isFeatured: true,
    isActive: true,
    tags: ["samsung", "m52", "galaxy", "hp bekas", "android", "5g"],
    createdAt: new Date("2025-08-10"),
  },
  {
    id: "hp-002",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Xiaomi Redmi Note 11 Bekas",
    slug: "xiaomi-redmi-note-11-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-xiaomi",
    modelId: "xmi-note11",
    condition: "mulus",
    conditionLabel: "Mulus",
    conditionNote: "Seperti baru, fullset dus.",
    grade: "A",
    defects: [],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
      { label: "Fingerprint", status: "Normal" },
    ],
    accessories: ["Unit", "Charger", "Kabel", "Dus Fullset"],
    description:
      "Xiaomi Redmi Note 11 bekas kondisi mulus seperti baru. Fullset dengan dus dan aksesori. Layar AMOLED 90Hz, Snapdragon 680, RAM 6GB, storage 128GB. Baterai 5000mAh fast charging 33W.",
    specifications: {
      Merek: "Xiaomi",
      Tipe: "Redmi Note 11",
      Chipset: "Snapdragon 680",
      RAM: "6 GB",
      Storage: "128 GB",
      Baterai: "5000 mAh",
      "Fast Charging": "33W",
      Layar: "6.43 inch AMOLED 90Hz",
      "Kamera Belakang": "50 MP + 8 MP + 2 MP + 2 MP",
      "Kamera Depan": "13 MP",
      Kondisi: "Mulus seperti baru, fullset",
      Garansi: "7 hari garansi toko",
    },
    price: 1450000,
    compareAtPrice: 1800000,
    stock: 2,
    images: [samsungM52],
    warranty: "7 hari garansi toko",
    weight: 280,
    rating: 4.9,
    reviewCount: 8,
    soldCount: 15,
    isFeatured: true,
    isActive: true,
    tags: ["xiaomi", "redmi", "note 11", "hp bekas", "android", "amoled"],
    createdAt: new Date("2025-08-09"),
  },
  {
    id: "hp-003",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Samsung Galaxy A32 Bekas",
    slug: "samsung-galaxy-a32-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-samsung",
    modelId: "sam-a32",
    condition: "normal",
    conditionLabel: "Normal",
    conditionNote: "Layar AMOLED, mesin normal.",
    grade: "B",
    defects: ["Bekas pemakaian normal di body", "Baterai health ±90%"],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
      { label: "Baterai", status: "Minus", note: "Health ±90%" },
    ],
    accessories: ["Unit", "Charger"],
    description:
      "Samsung Galaxy A32 bekas kondisi normal. Layar Super AMOLED 90Hz. Kamera 64MP, baterai 5000mAh. Cocok untuk sehari-hari.",
    specifications: {
      Merek: "Samsung",
      Tipe: "Galaxy A32",
      Chipset: "Helio G80",
      RAM: "6 GB",
      Storage: "128 GB",
      Baterai: "5000 mAh",
      Layar: "6.4 inch Super AMOLED 90Hz",
      "Kamera Belakang": "64 MP + 8 MP + 5 MP + 5 MP",
      "Kamera Depan": "20 MP",
      Garansi: "3 hari garansi toko",
    },
    price: 1100000,
    compareAtPrice: 1500000,
    stock: 2,
    images: [samsungM52],
    warranty: "3 hari garansi toko",
    weight: 280,
    rating: 4.7,
    reviewCount: 15,
    soldCount: 32,
    isFeatured: false,
    isActive: true,
    tags: ["samsung", "a32", "galaxy", "hp bekas", "android", "amoled"],
    createdAt: new Date("2025-08-08"),
  },
  {
    id: "hp-004",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Oppo A76 Bekas",
    slug: "oppo-a76-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-oppo",
    modelId: "oppo-a76",
    condition: "normal",
    conditionLabel: "Normal",
    conditionNote: "Baterai awet, mesin stabil.",
    grade: "B",
    defects: ["Gores halus di bagian belakang"],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
    ],
    accessories: ["Unit", "Charger"],
    description:
      "Oppo A76 bekas kondisi normal. Baterai besar 5000mAh, RAM 6GB, storage 128GB. Kamera 13MP. Cocok untuk penggunaan normal.",
    specifications: {
      Merek: "Oppo",
      Tipe: "A76",
      Chipset: "Snapdragon 680",
      RAM: "6 GB",
      Storage: "128 GB",
      Baterai: "5000 mAh",
      "Fast Charging": "33W",
      Layar: "6.56 inch IPS LCD 90Hz",
      "Kamera Belakang": "13 MP + 2 MP",
      "Kamera Depan": "8 MP",
      Garansi: "3 hari garansi toko",
    },
    price: 1050000,
    compareAtPrice: 1300000,
    stock: 3,
    images: [samsungM52],
    warranty: "3 hari garansi toko",
    weight: 290,
    rating: 4.6,
    reviewCount: 10,
    soldCount: 20,
    isFeatured: false,
    isActive: true,
    tags: ["oppo", "a76", "hp bekas", "android"],
    createdAt: new Date("2025-08-07"),
  },
  {
    id: "hp-005",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Vivo Y21 Bekas",
    slug: "vivo-y21-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-vivo",
    modelId: "vivo-y21",
    condition: "normal",
    conditionLabel: "Normal",
    conditionNote: "Ringan dan tipis, baterai awet.",
    grade: "B",
    defects: ["Bekas pemakaian normal di sisi frame"],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
    ],
    accessories: ["Unit", "Charger"],
    description:
      "Vivo Y21 bekas kondisi normal. Desain tipis dan ringan. Baterai 5000mAh, RAM 4GB, storage 64GB. Cocok untuk penggunaan ringan.",
    specifications: {
      Merek: "Vivo",
      Tipe: "Y21",
      Chipset: "Helio P35",
      RAM: "4 GB",
      Storage: "64 GB",
      Baterai: "5000 mAh",
      Layar: "6.51 inch IPS LCD",
      "Kamera Belakang": "13 MP + 2 MP",
      "Kamera Depan": "8 MP",
      Garansi: "3 hari garansi toko",
    },
    price: 850000,
    compareAtPrice: 1100000,
    stock: 2,
    images: [samsungM52],
    warranty: "3 hari garansi toko",
    weight: 270,
    rating: 4.5,
    reviewCount: 7,
    soldCount: 18,
    isFeatured: false,
    isActive: true,
    tags: ["vivo", "y21", "hp bekas", "android"],
    createdAt: new Date("2025-08-06"),
  },
  {
    id: "hp-006",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Realme 8i Bekas",
    slug: "realme-8i-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-realme",
    modelId: "realme-8i",
    condition: "mulus",
    conditionLabel: "Mulus",
    conditionNote: "Seperti baru, garansi masih ada.",
    grade: "A",
    defects: [],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
      { label: "Baterai", status: "Normal" },
    ],
    accessories: ["Unit", "Charger", "Kabel"],
    description:
      "Realme 8i bekas kondisi mulus. Layar 120Hz, Helio G96, RAM 6GB, storage 128GB. Baterai 5000mAh. Garansi resmi masih berlaku.",
    specifications: {
      Merek: "Realme",
      Tipe: "8i",
      Chipset: "Helio G96",
      RAM: "6 GB",
      Storage: "128 GB",
      Baterai: "5000 mAh",
      "Fast Charging": "18W",
      Layar: "6.6 inch IPS LCD 120Hz",
      "Kamera Belakang": "50 MP + 2 MP + 2 MP",
      "Kamera Depan": "16 MP",
      Kondisi: "Mulus, garansi resmi",
      Garansi: "14 hari garansi toko",
    },
    price: 1350000,
    compareAtPrice: 1700000,
    stock: 1,
    images: [samsungM52],
    warranty: "14 hari garansi toko",
    weight: 290,
    rating: 4.8,
    reviewCount: 5,
    soldCount: 12,
    isFeatured: true,
    isActive: true,
    tags: ["realme", "8i", "hp bekas", "android", "120hz"],
    createdAt: new Date("2025-08-05"),
  },
  {
    id: "hp-007",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "iPhone SE 2020 Bekas",
    slug: "iphone-se-2020-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-iphone",
    modelId: "iphone-se2020",
    condition: "normal",
    conditionLabel: "Normal",
    conditionNote: "Baterai 85%, normal untuk usia.",
    grade: "B+",
    defects: ["Baterai health 85% (masih dalam batas normal untuk usia)."],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
      { label: "Fingerprint", status: "Normal" },
      { label: "NFC", status: "Normal" },
      { label: "Baterai", status: "Minus", note: "Health 85%" },
    ],
    accessories: ["Unit"],
    description:
      "iPhone SE 2020 bekas kondisi normal. Chipset A13 Bionic, RAM 3GB, storage 64GB. Baterai 85% health. Cocok untuk yang ingin iPhone murah.",
    specifications: {
      Merek: "Apple",
      Tipe: "iPhone SE 2020",
      Chipset: "A13 Bionic",
      RAM: "3 GB",
      Storage: "64 GB",
      Baterai: "1821 mAh (85% health)",
      Layar: "4.7 inch Retina IPS LCD",
      "Kamera Belakang": "12 MP",
      "Kamera Depan": "7 MP",
      "Kondisi Baterai": "85% health",
      Garansi: "7 hari garansi toko",
    },
    price: 2200000,
    compareAtPrice: 2800000,
    stock: 1,
    images: [samsungM52],
    warranty: "7 hari garansi toko",
    weight: 250,
    rating: 4.7,
    reviewCount: 9,
    soldCount: 14,
    isFeatured: true,
    isActive: true,
    tags: ["iphone", "se", "2020", "hp bekas", "ios", "apple"],
    createdAt: new Date("2025-08-04"),
  },
  {
    id: "hp-008",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Tecno Pova 2 Bekas",
    slug: "tecno-pova-2-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-tecno",
    modelId: "tecno-pova2",
    condition: "normal",
    conditionLabel: "Normal",
    conditionNote: "Baterai jumbo, gaming entry.",
    grade: "B",
    defects: ["Gores halus di bagian samping", "Bekas pemakaian normal"],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
      { label: "Baterai", status: "Minus", note: "Health ±88%" },
    ],
    accessories: ["Unit", "Charger"],
    description:
      "Tecno Pova 2 bekas kondisi normal. Baterai jumbo 7000mAh, layar 6.9 inch. Helio G85, RAM 6GB, storage 128GB. Cocok untuk gaming ringan.",
    specifications: {
      Merek: "Tecno",
      Tipe: "Pova 2",
      Chipset: "Helio G85",
      RAM: "6 GB",
      Storage: "128 GB",
      Baterai: "7000 mAh",
      Layar: "6.9 inch IPS LCD 90Hz",
      "Kamera Belakang": "48 MP + 2 MP + 2 MP",
      "Kamera Depan": "8 MP",
      Garansi: "3 hari garansi toko",
    },
    price: 1100000,
    compareAtPrice: 1500000,
    stock: 2,
    images: [samsungM52],
    warranty: "3 hari garansi toko",
    weight: 320,
    rating: 4.6,
    reviewCount: 6,
    soldCount: 11,
    isFeatured: false,
    isActive: true,
    tags: ["tecno", "pova", "hp bekas", "android", "gaming", "baterai besar"],
    createdAt: new Date("2025-08-03"),
  },
  {
    id: "hp-009",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Samsung Galaxy A53 5G Bekas",
    slug: "samsung-galaxy-a53-5g-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-samsung",
    modelId: "sam-a53",
    condition: "mulus",
    conditionLabel: "Mulus",
    conditionNote: "Mulus fullset, garansi resmi.",
    grade: "A",
    defects: [],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
      { label: "Baterai", status: "Normal" },
      { label: "Fingerprint", status: "Normal" },
    ],
    accessories: ["Unit", "Charger", "Kabel", "Dus Fullset"],
    description:
      "Samsung Galaxy A53 5G bekas kondisi mulus fullset. Layar Super AMOLED 120Hz, Exynos 1280, RAM 8GB, storage 256GB. IP67 tahan air.",
    specifications: {
      Merek: "Samsung",
      Tipe: "Galaxy A53 5G",
      Chipset: "Exynos 1280",
      RAM: "8 GB",
      Storage: "256 GB",
      Baterai: "5000 mAh",
      "Fast Charging": "25W",
      Layar: "6.5 inch Super AMOLED 120Hz",
      "Kamera Belakang": "64 MP + 12 MP + 5 MP + 5 MP",
      "Kamera Depan": "32 MP",
      "Tahan Air": "IP67",
      Garansi: "14 hari garansi toko",
    },
    price: 2800000,
    compareAtPrice: 3500000,
    stock: 1,
    images: [samsungM52],
    warranty: "14 hari garansi toko",
    weight: 300,
    rating: 4.9,
    reviewCount: 11,
    soldCount: 18,
    isFeatured: true,
    isActive: true,
    tags: ["samsung", "a53", "galaxy", "hp bekas", "android", "5g", "ip67"],
    createdAt: new Date("2025-08-02"),
  },
  {
    id: "hp-010",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Infinix Hot 11 Bekas",
    slug: "infinix-hot-11-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-infinix",
    modelId: "infinix-hot11",
    condition: "normal",
    conditionLabel: "Normal",
    conditionNote: "Layar besar, baterai awet.",
    grade: "B",
    defects: ["Gores halus di layar bagian pojok"],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
    ],
    accessories: ["Unit", "Charger"],
    description:
      "Infinix Hot 11 bekas kondisi normal. Layar besar 6.78 inch FHD+, Helio G88, RAM 4GB, storage 64GB. Baterai 5200mAh.",
    specifications: {
      Merek: "Infinix",
      Tipe: "Hot 11",
      Chipset: "Helio G88",
      RAM: "4 GB",
      Storage: "64 GB",
      Baterai: "5200 mAh",
      Layar: "6.78 inch FHD+ IPS LCD",
      "Kamera Belakang": "50 MP + 2 MP",
      "Kamera Depan": "8 MP",
      Garansi: "3 hari garansi toko",
    },
    price: 750000,
    compareAtPrice: 1000000,
    stock: 3,
    images: [samsungM52],
    warranty: "3 hari garansi toko",
    weight: 300,
    rating: 4.4,
    reviewCount: 5,
    soldCount: 16,
    isFeatured: false,
    isActive: true,
    tags: ["infinix", "hot 11", "hp bekas", "android"],
    createdAt: new Date("2025-08-01"),
  },

  // ========== SPAREPART ==========
  {
    id: "sp-001",
    sellerId: "seller-mubarok",
    type: "sparepart",
    name: "LCD Samsung Galaxy A32 Original",
    slug: "lcd-samsung-galaxy-a32-original",
    categoryId: "cat-lcd",
    compatibleWith: ["sam-a32"],
    brandId: "brand-samsung",
    modelId: null,
    condition: "ori-copotan",
    conditionLabel: "Ori Copotan",
    conditionNote: "LCD original copotan, kondisi mulus.",
    tested: true,
    isOriginal: true,
    quality: "Mulus",
    description:
      "LCD Samsung Galaxy A32 original copotan. Kondisi mulus, berfungsi sempurna. Cocok untuk pengganti LCD yang rusak atau retak.",
    specifications: {
      Kompatibel: "Samsung Galaxy A32",
      Tipe: "Super AMOLED",
      Ukuran: "6.4 inch",
      Resolusi: "1080 x 2400",
      Kondisi: "Original Copotan — Mulus",
      Garansi: "7 hari",
    },
    price: 350000,
    compareAtPrice: null,
    stock: 3,
    images: [samsungM52],
    warranty: "7 hari",
    weight: 50,
    rating: 4.8,
    reviewCount: 14,
    soldCount: 28,
    isFeatured: true,
    isActive: true,
    tags: ["lcd", "samsung", "a32", "amoled", "original", "copotan"],
    createdAt: new Date("2025-08-10"),
  },
  {
    id: "sp-002",
    sellerId: "seller-mubarok",
    type: "sparepart",
    name: "Baterai Xiaomi Redmi Note 11 Original",
    slug: "baterai-xiaomi-redmi-note-11-original",
    categoryId: "cat-baterai",
    compatibleWith: ["xmi-note11"],
    brandId: "brand-xiaomi",
    modelId: null,
    condition: "ori-copotan",
    conditionLabel: "Ori Copotan",
    conditionNote: "Baterai original, kapasitas penuh.",
    tested: true,
    isOriginal: true,
    quality: "Bagus",
    description:
      "Baterai Xiaomi Redmi Note 11 original copotan. Kapasitas 5000mAh, kondisi masih bagus. Cocok untuk pengganti baterai soak.",
    specifications: {
      Kompatibel: "Xiaomi Redmi Note 11",
      Kapasitas: "5000 mAh",
      Tipe: "Li-Po",
      Kondisi: "Original Copotan",
      Garansi: "7 hari",
    },
    price: 125000,
    compareAtPrice: null,
    stock: 5,
    images: [samsungM52],
    warranty: "7 hari",
    weight: 80,
    rating: 4.7,
    reviewCount: 9,
    soldCount: 22,
    isFeatured: false,
    isActive: true,
    tags: ["baterai", "xiaomi", "redmi", "note 11", "original"],
    createdAt: new Date("2025-08-09"),
  },
  {
    id: "sp-003",
    sellerId: "seller-mubarok",
    type: "sparepart",
    name: "Charging Port Samsung A12 Compatible",
    slug: "charging-port-samsung-a12-compatible",
    categoryId: "cat-charging",
    compatibleWith: ["sam-a12"],
    brandId: "brand-samsung",
    modelId: null,
    condition: "compatible",
    conditionLabel: "Compatible",
    conditionNote: "Kualitas bagus, tested.",
    tested: true,
    isOriginal: false,
    quality: "Bagus",
    description:
      "Charging port / konektor charger Samsung Galaxy A12 compatible. Kualitas bagus, sudah tested. Cocok untuk pengganti port charger yang rusak.",
    specifications: {
      Kompatibel: "Samsung Galaxy A12",
      Tipe: "USB-C Charging Port",
      Kondisi: "Compatible — Tested",
      Garansi: "3 hari",
    },
    price: 45000,
    compareAtPrice: null,
    stock: 10,
    images: [samsungM52],
    warranty: "3 hari",
    weight: 20,
    rating: 4.5,
    reviewCount: 7,
    soldCount: 35,
    isFeatured: false,
    isActive: true,
    tags: ["charging", "port", "samsung", "a12", "compatible"],
    createdAt: new Date("2025-08-08"),
  },
  {
    id: "sp-004",
    sellerId: "seller-mubarok",
    type: "sparepart",
    name: "Back Cover Oppo A16 Original",
    slug: "back-cover-oppo-a16-original",
    categoryId: "cat-casing",
    compatibleWith: ["oppo-a16"],
    brandId: "brand-oppo",
    modelId: null,
    condition: "ori-copotan",
    conditionLabel: "Ori Copotan",
    conditionNote: "Back cover original, warna hitam.",
    tested: true,
    isOriginal: true,
    quality: "Mulus",
    description:
      "Back cover / casing belakang Oppo A16 original copotan. Warna hitam, kondisi mulus. Cocok untuk pengganti casing belakang yang pecah.",
    specifications: {
      Kompatibel: "Oppo A16",
      Tipe: "Back Cover / Casing Belakang",
      Warna: "Hitam",
      Kondisi: "Original Copotan — Mulus",
      Garansi: "3 hari",
    },
    price: 75000,
    compareAtPrice: null,
    stock: 4,
    images: [samsungM52],
    warranty: "3 hari",
    weight: 30,
    rating: 4.6,
    reviewCount: 5,
    soldCount: 12,
    isFeatured: false,
    isActive: true,
    tags: ["back cover", "casing", "oppo", "a16", "original"],
    createdAt: new Date("2025-08-07"),
  },
  {
    id: "sp-005",
    sellerId: "seller-mubarok",
    type: "sparepart",
    name: "S Pen Samsung Galaxy Note 8 - Original Copotan",
    slug: "s-pen-samsung-galaxy-note-8-ori-copotan",
    categoryId: "cat-aksesori",
    compatibleWith: ["sam-note8"],
    brandId: "brand-samsung",
    modelId: null,
    condition: "ori-copotan",
    conditionLabel: "Ori Copotan",
    conditionNote: "Kondisi normal, berfungsi baik.",
    tested: true,
    isOriginal: true,
    quality: "Normal",
    description:
      "S Pen Samsung Galaxy Note 8 original copotan. Kondisi normal, stylus berfungsi baik. Cocok untuk pengganti S Pen yang hilang atau rusak.",
    specifications: {
      Kompatibel: "Samsung Galaxy Note 8",
      Tipe: "S Pen Stylus",
      Kondisi: "Original Copotan — Normal",
      Warna: "Hitam",
      Garansi: "3 hari",
    },
    price: 85000,
    compareAtPrice: null,
    stock: 2,
    images: [spenNote8],
    warranty: "3 hari",
    weight: 20,
    rating: 4.8,
    reviewCount: 11,
    soldCount: 19,
    isFeatured: true,
    isActive: true,
    tags: ["s pen", "stylus", "samsung", "note 8", "aksesori", "original"],
    createdAt: new Date("2025-08-06"),
  },
  {
    id: "sp-006",
    sellerId: "seller-mubarok",
    type: "sparepart",
    name: "Modul Kamera Depan Vivo Y20 Original",
    slug: "modul-kamera-depan-vivo-y20-original",
    categoryId: "cat-kamera",
    compatibleWith: ["vivo-y20"],
    brandId: "brand-vivo",
    modelId: null,
    condition: "ori-copotan",
    conditionLabel: "Ori Copotan",
    conditionNote: "Kamera jernih, berfungsi normal.",
    tested: true,
    isOriginal: true,
    quality: "Normal",
    description:
      "Modul kamera depan Vivo Y20 original copotan. Kondisi normal, hasil jernih. Cocok untuk pengganti kamera depan yang rusak.",
    specifications: {
      Kompatibel: "Vivo Y20",
      Tipe: "Front Camera Module",
      Resolusi: "8 MP",
      Kondisi: "Original Copotan — Normal",
      Garansi: "3 hari",
    },
    price: 65000,
    compareAtPrice: null,
    stock: 3,
    images: [samsungM52],
    warranty: "3 hari",
    weight: 10,
    rating: 4.5,
    reviewCount: 4,
    soldCount: 8,
    isFeatured: false,
    isActive: true,
    tags: ["kamera", "depan", "vivo", "y20", "original"],
    createdAt: new Date("2025-08-05"),
  },
  {
    id: "sp-007",
    sellerId: "seller-mubarok",
    type: "sparepart",
    name: "Loud Speaker Realme C21 Compatible",
    slug: "loud-speaker-realme-c21-compatible",
    categoryId: "cat-audio",
    compatibleWith: ["realme-c21"],
    brandId: "brand-realme",
    modelId: null,
    condition: "compatible",
    conditionLabel: "Compatible",
    conditionNote: "Suara jernih, sudah tested.",
    tested: true,
    isOriginal: false,
    quality: "Bagus",
    description:
      "Loud speaker / speaker utama Realme C21 compatible. Suara jernih dan keras. Sudah tested sebelum dikirim.",
    specifications: {
      Kompatibel: "Realme C21",
      Tipe: "Loud Speaker",
      Kondisi: "Compatible — Tested",
      Garansi: "3 hari",
    },
    price: 35000,
    compareAtPrice: null,
    stock: 8,
    images: [samsungM52],
    warranty: "3 hari",
    weight: 15,
    rating: 4.4,
    reviewCount: 6,
    soldCount: 18,
    isFeatured: false,
    isActive: true,
    tags: ["speaker", "loud", "realme", "c21", "compatible"],
    createdAt: new Date("2025-08-04"),
  },
  {
    id: "sp-008",
    sellerId: "seller-mubarok",
    type: "sparepart",
    name: "Flex Cable Kamera Samsung A22 Original",
    slug: "flex-cable-kamera-samsung-a22-original",
    categoryId: "cat-flex",
    compatibleWith: ["sam-a22"],
    brandId: "brand-samsung",
    modelId: null,
    condition: "ori-copotan",
    conditionLabel: "Ori Copotan",
    conditionNote: "Flex kamera original, berfungsi normal.",
    tested: true,
    isOriginal: true,
    quality: "Normal",
    description:
      "Flex cable kamera Samsung Galaxy A22 original copotan. Kondisi normal, berfungsi baik. Cocok untuk pengganti flex yang putus.",
    specifications: {
      Kompatibel: "Samsung Galaxy A22",
      Tipe: "Camera Flex Cable",
      Kondisi: "Original Copotan — Normal",
      Garansi: "3 hari",
    },
    price: 55000,
    compareAtPrice: null,
    stock: 4,
    images: [samsungM52],
    warranty: "3 hari",
    weight: 10,
    rating: 4.6,
    reviewCount: 3,
    soldCount: 7,
    isFeatured: false,
    isActive: true,
    tags: ["flex", "cable", "kamera", "samsung", "a22", "original"],
    createdAt: new Date("2025-08-03"),
  },

  {
    id: "hp-s23",
    sellerId: "seller-mubarok",
    type: "hp-bekas",
    name: "Samsung Galaxy S23 Bekas",
    slug: "samsung-galaxy-s23-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-samsung",
    modelId: "sam-s23",
    condition: "normal",
    conditionLabel: "Normal",
    conditionNote: "Layar normal, touch normal, kamera normal. Body ada goresan ringan.",
    grade: "B+",
    defects: ["Frame kanan terdapat gores ringan.", "Back cover terdapat bekas pemakaian."],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
      { label: "Fingerprint", status: "Normal" },
      { label: "NFC", status: "Normal" },
    ],
    accessories: ["Unit", "Charger"],
    description:
      "Samsung Galaxy S23 bekas. Snapdragon 8 Gen 2, 8/256. Layar Super AMOLED 120Hz, kamera 50MP. Body terdapat gores ringan, kelengkapan unit + charger. Garansi toko 30 hari.",
    specifications: {
      Merek: "Samsung",
      Tipe: "Galaxy S23",
      Chipset: "Snapdragon 8 Gen 2",
      RAM: "8 GB",
      Storage: "256 GB",
      Baterai: "3900 mAh",
      Layar: "6.1 inch Super AMOLED 120Hz",
      "Kamera Belakang": "50 MP + 12 MP + 10 MP",
      "Kamera Depan": "12 MP",
      "Kondisi Body": "Gores ringan pada frame",
      Garansi: "30 hari garansi toko",
    },
    price: 5900000,
    compareAtPrice: 6500000,
    stock: 1,
    images: [samsungM52],
    warranty: "30 hari garansi toko",
    weight: 330,
    rating: 4.9,
    reviewCount: 20,
    soldCount: 35,
    isFeatured: true,
    isActive: true,
    tags: ["samsung", "s23", "galaxy", "hp bekas", "android", "5g"],
    createdAt: new Date("2025-08-12"),
  },
  // ========== TABLET ==========
  {
    id: "tb-001",
    sellerId: "seller-mubarok",
    type: "tablet",
    name: "Samsung Galaxy Tab A7 Lite Bekas",
    slug: "samsung-galaxy-tab-a7-lite-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-samsung",
    modelId: null,
    condition: "normal",
    conditionLabel: "Normal",
    conditionNote: "Layar 8.7 inch, ringan.",
    grade: "B+",
    defects: ["Bekas pemakaian normal di back cover"],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
    ],
    accessories: ["Unit", "Charger", "Kabel"],
    description:
      "Samsung Galaxy Tab A7 Lite bekas kondisi normal. Layar 8.7 inch, Helio P22T, RAM 3GB, storage 32GB. Cocok untuk media consumption.",
    specifications: {
      Merek: "Samsung",
      Tipe: "Galaxy Tab A7 Lite",
      Chipset: "Helio P22T",
      RAM: "3 GB",
      Storage: "32 GB",
      Layar: "8.7 inch TFT LCD",
      "Kamera Belakang": "8 MP",
      "Kamera Depan": "2 MP",
      Baterai: "5100 mAh",
      Garansi: "7 hari garansi toko",
    },
    price: 1200000,
    compareAtPrice: 1600000,
    stock: 1,
    images: [samsungM52],
    warranty: "7 hari garansi toko",
    weight: 370,
    rating: 4.7,
    reviewCount: 8,
    soldCount: 12,
    isFeatured: true,
    isActive: true,
    tags: ["samsung", "tab", "a7", "lite", "tablet", "bekas"],
    createdAt: new Date("2025-08-10"),
  },
  {
    id: "tb-002",
    sellerId: "seller-mubarok",
    type: "tablet",
    name: "Xiaomi Redmi Pad SE Bekas",
    slug: "xiaomi-redmi-pad-se-bekas",
    categoryId: null,
    compatibleWith: [],
    brandId: "brand-xiaomi",
    modelId: null,
    condition: "mulus",
    conditionLabel: "Mulus",
    conditionNote: "Mulus, fullset aksesoris.",
    grade: "A",
    defects: [],
    inspection: [
      { label: "Layar", status: "Normal" },
      { label: "Touchscreen", status: "Normal" },
      { label: "Kamera", status: "Normal" },
      { label: "Speaker", status: "Normal" },
      { label: "Charging", status: "Normal" },
    ],
    accessories: ["Unit", "Charger", "Kabel", "Dus Fullset"],
    description:
      "Xiaomi Redmi Pad SE bekas kondisi mulus. Layar 11 inch 90Hz, Snapdragon 680, RAM 4GB, storage 128GB. Fullset dengan aksesoris.",
    specifications: {
      Merek: "Xiaomi",
      Tipe: "Redmi Pad SE",
      Chipset: "Snapdragon 680",
      RAM: "4 GB",
      Storage: "128 GB",
      Layar: "11 inch IPS LCD 90Hz",
      "Kamera Belakang": "8 MP",
      "Kamera Depan": "8 MP",
      Baterai: "8000 mAh",
      "Fast Charging": "18W",
      Garansi: "14 hari garansi toko",
    },
    price: 1800000,
    compareAtPrice: 2300000,
    stock: 1,
    images: [samsungM52],
    warranty: "14 hari garansi toko",
    weight: 520,
    rating: 4.8,
    reviewCount: 6,
    soldCount: 9,
    isFeatured: true,
    isActive: true,
    tags: ["xiaomi", "redmi", "pad", "se", "tablet", "bekas"],
    createdAt: new Date("2025-08-09"),
  },
];

export function findProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug === slug);
}

export function findBrand(id: string): PhoneBrand | undefined {
  return mockBrands.find((b) => b.id === id);
}

export function findModel(id: string | null): PhoneModel | undefined {
  if (!id) return undefined;
  for (const b of mockBrands) {
    const m = b.models.find((mm) => mm.id === id);
    if (m) return m;
  }
  return undefined;
}

export function findCategory(id: string | null): SparePartCategory | undefined {
  if (!id) return undefined;
  return mockCategories.find((c) => c.id === id);
}
