/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ServiceNewRouteImport } from './routes/service-new'
import { Route as RepairTrackerRouteImport } from './routes/repair-tracker'
import { Route as ProdukRouteImport } from './routes/produk'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukSlugRouteImport } from './routes/produk_.$slug'
import { Route as RepairTrackerTicketIdInvoiceRouteImport } from './routes/repair-tracker.$ticketId.invoice'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceNewRoute = ServiceNewRouteImport.update({
  id: '/service-new',
  path: '/service-new',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairTrackerRoute = RepairTrackerRouteImport.update({
  id: '/repair-tracker',
  path: '/repair-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukRoute = ProdukRouteImport.update({
  id: '/produk',
  path: '/produk',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukSlugRoute = ProdukSlugRouteImport.update({
  id: '/produk_/$slug',
  path: '/produk/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairTrackerTicketIdInvoiceRoute =
  RepairTrackerTicketIdInvoiceRouteImport.update({
    id: '/$ticketId/invoice',
    path: '/$ticketId/invoice',
    getParentRoute: () => RepairTrackerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/produk': typeof ProdukRoute
  '/repair-tracker': typeof RepairTrackerRouteWithChildren
  '/service-new': typeof ServiceNewRoute
  '/tentang': typeof TentangRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/repair-tracker/$ticketId/invoice': typeof RepairTrackerTicketIdInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/produk': typeof ProdukRoute
  '/repair-tracker': typeof RepairTrackerRouteWithChildren
  '/service-new': typeof ServiceNewRoute
  '/tentang': typeof TentangRoute
  '/produk/$slug': typeof ProdukSlugRoute
  '/repair-tracker/$ticketId/invoice': typeof RepairTrackerTicketIdInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/produk': typeof ProdukRoute
  '/repair-tracker': typeof RepairTrackerRouteWithChildren
  '/service-new': typeof ServiceNewRoute
  '/tentang': typeof TentangRoute
  '/produk_/$slug': typeof ProdukSlugRoute
  '/repair-tracker/$ticketId/invoice': typeof RepairTrackerTicketIdInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/inventory'
    | '/produk'
    | '/repair-tracker'
    | '/service-new'
    | '/tentang'
    | '/produk/$slug'
    | '/repair-tracker/$ticketId/invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/inventory'
    | '/produk'
    | '/repair-tracker'
    | '/service-new'
    | '/tentang'
    | '/produk/$slug'
    | '/repair-tracker/$ticketId/invoice'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/dashboard'
    | '/inventory'
    | '/produk'
    | '/repair-tracker'
    | '/service-new'
    | '/tentang'
    | '/produk_/$slug'
    | '/repair-tracker/$ticketId/invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  ProdukRoute: typeof ProdukRoute
  RepairTrackerRoute: typeof RepairTrackerRouteWithChildren
  ServiceNewRoute: typeof ServiceNewRoute
  TentangRoute: typeof TentangRoute
  ProdukSlugRoute: typeof ProdukSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-new': {
      id: '/service-new'
      path: '/service-new'
      fullPath: '/service-new'
      preLoaderRoute: typeof ServiceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-tracker': {
      id: '/repair-tracker'
      path: '/repair-tracker'
      fullPath: '/repair-tracker'
      preLoaderRoute: typeof RepairTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk': {
      id: '/produk'
      path: '/produk'
      fullPath: '/produk'
      preLoaderRoute: typeof ProdukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk_/$slug': {
      id: '/produk_/$slug'
      path: '/produk/$slug'
      fullPath: '/produk/$slug'
      preLoaderRoute: typeof ProdukSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair-tracker/$ticketId/invoice': {
      id: '/repair-tracker/$ticketId/invoice'
      path: '/$ticketId/invoice'
      fullPath: '/repair-tracker/$ticketId/invoice'
      preLoaderRoute: typeof RepairTrackerTicketIdInvoiceRouteImport
      parentRoute: typeof RepairTrackerRoute
    }
  }
}

interface RepairTrackerRouteChildren {
  RepairTrackerTicketIdInvoiceRoute: typeof RepairTrackerTicketIdInvoiceRoute
}

const RepairTrackerRouteChildren: RepairTrackerRouteChildren = {
  RepairTrackerTicketIdInvoiceRoute: RepairTrackerTicketIdInvoiceRoute,
}

const RepairTrackerRouteWithChildren = RepairTrackerRoute._addFileChildren(
  RepairTrackerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  ProdukRoute: ProdukRoute,
  RepairTrackerRoute: RepairTrackerRouteWithChildren,
  ServiceNewRoute: ServiceNewRoute,
  TentangRoute: TentangRoute,
  ProdukSlugRoute: ProdukSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
